[theme]
primaryColor = "#3FBECE"            # Custom primary color for buttons and highlights
backgroundColor = "#BDC0C2"         # Background color of the app
secondaryBackgroundColor = "#FAFBFA" # Background color for sidebar and widgets
textColor = "#FAFBFA"               # Text color for main content
font = "sans serif"                 # Font family (options: sans serif, serif, monospace)
